pom.xml, src/main/java/jenkins/metrics/api/Metrics.java
involves a group id change but the package names are the same.
Also fix a bug caught by findbugs
@reviewbybees
=> Upgrade the version of metrics to 3.1.2

src/main/java/jenkins/metrics/api/Metrics.java, src/main/java/jenkins/metrics/util/HealthChecksThreadPool.java, src/test/java/jenkins/metrics/api/HealthCheckProviderForTesting.java, src/test/java/jenkins/metrics/api/HealthCheckerTest.java
If more than 3 checks are put in the pool before one finishes a RejectedExecutionException is thrown,
never logged anywhere, and nothing is returned from registry.runHealthChecks
@reviewbybees
=> [JENKINS-32695] Result from health checks are lost when more than 3 run at the same time

src/main/java/jenkins/metrics/api/Metrics.java, src/main/java/jenkins/metrics/api/MetricsRootAction.java
=> [JENKINS-32696] Healthcheck API endpoint causes a new run of health checks

src/main/java/jenkins/metrics/api/Metrics.java
This allows Jenkins to work easily with other monitoring tools &
services that have ready-made JMX connectivity, such as:
1. DataDog: http://docs.datadoghq.com/integrations/java/
2. NewRelic: https://docs.newrelic.com/docs/agents/java-agent/custom-instrumentation/custom-jmx-instrumentation-yaml
3. Prometheus: https://github.com/prometheus/jmx_exporter
4. CollectD: https://collectd.org/wiki/index.php/Plugin:GenericJMX
5. IBM Tivoli: https://www.ibm.com/support/knowledgecenter/SSTFXA_6.3.0/com.ibm.itm.doc_6.3/builder/ab_ds_jmx_config.htm
6. Nagios: https://exchange.nagios.org/directory/Plugins/Java-Applications-and-Servers/check_jmx/details
=> Expose metrics via JMX

src/main/java/jenkins/metrics/api/Metrics.java
See [JENKINS-44486](https://issues.jenkins-ci.org/browse/JENKINS-44486).
I confirmed that installing the mesos plugin (which defines a [custom health check](https://github.com/jenkinsci/mesos-plugin/blob/master/src/main/java/org/jenkinsci/plugins/mesos/MesosHealthCheck.java)) without restarting Jenkins results in `UnsupportedOperationException`s being logged before this change, and does not cause exceptions after the change.
Since the change appears to be simple and isolated (the `defined` set is only used from line 606 to 615), I have not added any automated tests (famous last words), but am happy to do so if desired.
@reviewbybees
=> [JENKINS-44486] Prevent UnsupportedOperationException when installing plugins with custom health checks.

pom.xml, src/main/java/jenkins/metrics/api/Metrics.java, src/test/java/jenkins/metrics/api/MetricsTest.java
Adjust the metrics-plugin to put logs under the now configurable logs root directory, introduced in Jenkins 2.114+ since [JENKINS-50291](https://issues.jenkins-ci.org/browse/JENKINS-50291).
To test this change:
```shell
mvn clean verify # => MetricsTest will be skipped because < 2.114
mvn clean verify -Dtest=MetricsTest -Djenkins.version=2.114 -Denforcer.skip=true # MetricsTest run successfully. Enforcer must be skipped to avoid failure because of bytecode version checks
```
@reviewbybees esp. @stephenc
=> [JENKINS-50291] Move health-checker.log under the now configurable logs root directory

src/main/java/jenkins/metrics/api/MetricsAccessKey.java
Added compatibility with Configuration as code plugin - requested in [JCasc#169](https://github.com/jenkinsci/configuration-as-code-plugin/issues/169)
I must admit I'm guessing here - so it was tested and allows to configure the plugin with [JCasC](https://github.com/jenkinsci/configuration-as-code-plugin) but not sure if it's a right or rather dumb way of implementing it 
cc @ndeloof @batmat
=> DataBoundSetter for accessKeys - JCasC compatibility

src/main/java/jenkins/metrics/impl/JenkinsMetricProviderImpl.java, src/main/java/jenkins/metrics/impl/SubTaskTimeInQueueAction.java, src/main/java/jenkins/metrics/impl/TimeInQueueAction.java, src/main/resources/jenkins/metrics/impl/TimeInQueueAction/index.jelly, src/main/resources/jenkins/metrics/impl/TimeInQueueAction/index.properties, src/main/resources/jenkins/metrics/impl/TimeInQueueAction/summary.jelly
See [JENKINS-52075](https://issues.jenkins-ci.org/browse/JENKINS-52075)
=> [JENKINS-52075] Track the cumulative execution time of Pipeline jobs

src/main/java/jenkins/metrics/api/Metrics.java, src/test/java/jenkins/metrics/api/MetricsTest.java
https://issues.jenkins-ci.org/browse/JENKINS-57909
On top of #47, see the [commit](https://github.com/jenkinsci/metrics-plugin/pull/48/commits/1cd437638885595f81dedfdfde9f5e0e088df198) to review
@jglick
=> [JENKINS-57909] JMX: VM and System metrics shouldn't be exported

pom.xml
Executing PCT against newer jenkins versions fails with the following trace:
```
Error MessageThe log should have 'MetricsAccessKey.key = tDdG5Vsv-2-WDdHfI3QFPiU9-hcvKmWd2HL4CfVIFvUumQzz3qf6c0qt_HU4_lUh'Stacktracejava.lang.AssertionError: The log should have 'MetricsAccessKey.key = tDdG5Vsv-2-WDdHfI3QFPiU9-hcvKmWd2HL4CfVIFvUumQzz3qf6c0qt_HU4_lUh'at org.junit.Assert.fail(Assert.java:88)at org.junit.Assert.assertTrue(Assert.java:41)at io.jenkins.plugins.casc.misc.RoundTripAbstractTest.assertLogAsExpected(RoundTripAbstractTest.java:193)
```
After updating the JCasC version to latest one, the PCT succeeds.
@alecharp 
@oleg-nenashev @rsandell @varyvol @MRamonLeon
=> Update JCasC version to fix PCT errors

Jenkinsfile
(Edited description after the fact, for better up-front clarity)
For some unclear reason iI did not spend hours investigating, #58 PR was green. BUT the `master` branch started failing when it got merged.
The reason is that the `jenkins.version` in one combinatorial of `recommendedConfiguration` (2.164, which is older than `jenkins.version` of the metrics-plugin currently).is more 
This PR is fixing the Jenkinsfile by "exploding" the recommendedConfiguration with the various axis to be tested. This way we have control on the LTS to use (and it's bumped to the one declared in the pom.xml).
=> Fix CI failure

Jenkinsfile, src/main/java/jenkins/metrics/impl/JenkinsMetricProviderImpl.java, src/test/java/jenkins/metrics/impl/JenkinsMetricProviderImplTest.java
notifyQueued wasn't used at all. 
Also added tests for completion.
=> JENKINS-63760 notifyQueued used

pom.xml
@joseblas was testing a version of this plugin that included #70, and I noticed that he had to add an explicit dependency on `slf4j-api` to solve an upper bounds conflict between this plugin and core, which should not be necessary. The problem appears to be the way dependency conflicts were fixed in https://github.com/jenkinsci/metrics-plugin/commit/38c3baa868fa4eedf26cc521ddbc1735f6b29505. Since [`slf4j-api` is in the core BOM](https://github.com/jenkinsci/jenkins/blob/7aa52381f8d716f19ff71d7cf37970767ed5bbac/bom/pom.xml#L111), any conflicts with it in a plugin must be solved by excluding the dependency from all paths other than core, which in this case means that all of the Dropwizard metrics library dependencies need an exclusion.
At runtime, the version from Jenkins core is what is …
=> Plugins should use slf4j-api version from Jenkins core

src/main/java/jenkins/metrics/impl/JenkinsMetricProviderImpl.java
Do not just check `AbstractProject`, but any `ParameterizedJobMixIn.ParameterizedJob` including `WorkflowRun`, for `isDisabled`.
=> Support `WorkflowRun.isDisabled`

pom.xml, src/main/resources/index.jelly
Getting this released and adopted in `support-core` will help us cross the recent `jackson2-api` flag day and restore `support-core` to jenkinsci/bom as described in https://github.com/jenkinsci/bom/pull/1011, https://github.com/jenkinsci/support-core-plugin/pull/360, and https://github.com/jenkinsci/bom/pull/1016.
CC @alecharp @jetersen
=> Update plugin parent POM and BOM

pom.xml
unblocking https://github.com/jenkinsci/bom/pull/1275
Bumps [bom-2.346.x](https://github.com/jenkinsci/bom) from 1438.v6a_2c29d73f82 to 1500.ve4d05cd32975.
- [Release notes](https://github.com/jenkinsci/bom/releases)
- [Commits](https://github.com/jenkinsci/bom/commits)
---
updated-dependencies:
- dependency-name: io.jenkins.tools.bom:bom-2.346.x
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
=> Bump bom-2.346.x from 1438.v6a_2c29d73f82 to 1500.ve4d05cd32975

pom.xml, src/main/java/jenkins/metrics/impl/JenkinsMetricProviderImpl.java, src/test/java/jenkins/metrics/impl/JenkinsMetricProviderImplTest.java
[JENKINS-69817](https://issues.jenkins.io/browse/JENKINS-69817)
* Supersedes https://github.com/jenkinsci/metrics-plugin/pull/190 with tests. cc @sundergopalsingh
* Fixes a regression caused by https://github.com/jenkinsci/metrics-plugin/pull/127 using the same logic that was there, that is find the main owner using a `while` loop and compare it to the current completed task: 
```
Queue.Task owner = task.getOwnerTask();
while (owner != owner.getOwnerTask()) {
owner = owner.getOwnerTask();
}
if (owner != task) {
```
=> [JENKINS-69817] Fix addition of SubTaskTimeInQueueActions

Jenkinsfile, pom.xml, src/main/resources/jenkins/metrics/api/MetricsAccessKey/config.jelly, src/main/resources/jenkins/metrics/api/MetricsAccessKey/resource.css, src/main/resources/jenkins/metrics/api/MetricsAccessKey/resource.js
ping @basil 
Following https://www.jenkins.io/blog/2023/05/12/removing-prototype-from-jenkins to fix the different PrototypeJS usage done in the plugin.
For testing, I run the plugin locally with `mvn hpi:run` and created 2 new `MetricsAccessKey`, generating the token multiple time (saving it each time) to see that the javascript console was not throwing errors and the values were saved in the correct entry in the configuration file.
I also restarted the instance to make sure the previously configured entries were correctly loaded.
=> Fixes PrototypeJS usages

src/test/java/jenkins/metrics/impl/JenkinsMetricProviderImplTest.java
Observed in PCT:
```
java.lang.AssertionError: 
Expected: (a value greater than <2500L> and a value less than <3800L>)
but: a value less than <3800L> <3999L> was greater than <3800L>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
at jenkins.metrics.impl.JenkinsMetricProviderImplTest.given__a_job__when__built__then__events_and_metrics_include_build(JenkinsMetricProviderImplTest.java:140)
```
Introduced in #40. Amended in 57681f7, 9546e06, and 9546e06 (at least).
=> `JenkinsMetricProviderImplTest.given__a_job__when__built__then__events_and_metrics_include_build` is flaky

Jenkinsfile, pom.xml
Java 21 was released Sep 19, 2023. We want to announce full support for Java 21 in early October and would like the most used plugins to be compiled and tested with Java 21.
The acceptance test harness and plugin bill of materials tests are already passing with Java 21. This is a further step to improve plugin readiness for use with Java 21 and for development with Java 21.
The change intentionally tests only two Java configurations, Java 17 and Java 21 because we believe that the risk of a regression that only affects Java 11 is shallow. We generate Java 11 byte code with the Java 17 and the Java 21 builds, so we're already testing Java 11 byte code.
Testing done
===
Confirmed tests pass with Java 21 on Linux.
Supersedes pull request: #247.
Supersedes pull request: #250.
Supersedes pull …
=> Update parent POM, update dependencies, test with Java 21.

src/main/resources/jenkins/metrics/api/MetricsAccessKey/config.jelly, src/main/resources/jenkins/metrics/api/MetricsAccessKey/resource.js
https://issues.jenkins.io/browse/JENKINS-73950
Generating new keys on the Global Configuration page triggers the violation.
https://www.loom.com/share/a33cdd98e0344c698baf78e79ad7c4fb
https://www.loom.com/share/8484f3e7bbf546ee872616fdf842cdad
=> [JENKINS-73950] Extract inline event handler from `MetricsAccessKey/config.jelly`
