jenkinsci/metrics-plugin

src/main/java/jenkins/metrics/api/MetricsRootAction.java
=> An endpoint to return status 200 if everything is OK, status 417 otherwise

src/main/java/jenkins/metrics/util/AutoSamplingHistogram.java
=> [FIXED JENKINS-28620] Add better safety to the AutoSamplingHistogram

pom.xml, src/main/java/jenkins/metrics/api/MetricsAccessKey.java, src/main/java/jenkins/metrics/impl/JenkinsMetricProviderImpl.java, src/main/java/jenkins/metrics/impl/MetricsFilter.java
=> Enable publishing of FindBugs reports, bump FindBugs plugin version

src/main/java/jenkins/metrics/api/MetricProvider.java, src/main/java/jenkins/metrics/impl/JenkinsVersionsProviderImpl.java
=> Exposes details of various versions as metrics, which should make it easier to cross-correlate metric changes with version changes

pom.xml
@reviewbybees, specially @stephenc
=> Clean up. Some plugin updates.

src/main/resources/jenkins/metrics/api/MetricsAccessKey/config.jelly
[JENKINS-31054](https://issues.jenkins-ci.org/browse/JENKINS-31054)
@reviewbybees, specially @stephenc
=> [JENKINS-31054] Generate button does not work

src/main/java/jenkins/metrics/api/Metrics.java
Store and expose the last health check results
@reviewbybees
=> Expose health check results

src/main/java/jenkins/metrics/api/Metrics.java
Separate date stamp from preceding text
=> Improve log line readability

pom.xml
=> [JENKINS-34491] Fix PCT against core 2.0

src/main/java/jenkins/metrics/impl/JenkinsMetricProviderImpl.java, src/main/java/jenkins/metrics/impl/VMMetricProviderImpl.java
=> [FIXED JENKINS-36821] Adding history and windows to vm metrics

src/main/resources/jenkins/metrics/api/MetricsAccessKey/config.jelly
https://issues.jenkins-ci.org/browse/JENKINS-50722
=> [JENKINS-50722] origins field is not saved

src/main/java/jenkins/metrics/impl/JenkinsHealthCheckProviderImpl.java
The classes should probably match.
(This patch has not been tested, but seems obvious enough)
=> Fix test for healthcheck enablement

pom.xml, src/main/java/jenkins/metrics/api/Metrics.java, src/main/java/jenkins/metrics/api/MetricsAccessKey.java, src/main/java/jenkins/metrics/api/MetricsRootAction.java, src/main/java/jenkins/metrics/impl/JenkinsHealthCheckProviderImpl.java, src/main/java/jenkins/metrics/impl/JenkinsMetricProviderImpl.java, src/main/java/jenkins/metrics/impl/JenkinsVersionsProviderImpl.java
See [JENKINS-52061](https://issues.jenkins-ci.org/browse/JENKINS-52061)
=> [JENKINS-52061] Upgrade metrics to 4.0.2

pom.xml, src/main/java/jenkins/metrics/api/HealthCheckProviderListener.java, src/main/java/jenkins/metrics/api/MetricProviderListener.java, src/main/java/jenkins/metrics/api/Metrics.java, src/main/java/jenkins/metrics/api/MetricsAccessKey.java, src/main/java/jenkins/metrics/api/MetricsRootAction.java, src/main/java/jenkins/metrics/impl/JenkinsHealthCheckProviderImpl.java, src/main/java/jenkins/metrics/impl/JenkinsMetricProviderImpl.java, src/main/java/jenkins/metrics/impl/JenkinsVersionsProviderImpl.java
See [JENKINS-52067](https://issues.jenkins-ci.org/browse/JENKINS-52067)
On top of #35
=> [JENKINS-52067] Register metrics from dynamically installed plugins

src/main/java/jenkins/metrics/api/Metrics.java, src/main/java/jenkins/metrics/api/MetricsRootAction.java, src/main/java/jenkins/metrics/impl/JenkinsMetricProviderImpl.java, src/main/java/jenkins/metrics/util/AutoSamplingHistogram.java
See [JENKINS-52072](https://issues.jenkins-ci.org/browse/JENKINS-52072)
On top of #36
=>  [JENKINS-52072] Auto-register PeriodicWork implementations on Jenkins<2.129

pom.xml, src/main/java/jenkins/metrics/impl/JenkinsMetricProviderImpl.java, src/main/java/jenkins/metrics/impl/RunResolver.java, src/main/java/jenkins/metrics/impl/SubTaskTimeInQueueAction.java, src/main/java/jenkins/metrics/impl/TimeInQueueAction.java, src/main/resources/jenkins/metrics/impl/TimeInQueueAction/summary.jelly, src/main/resources/jenkins/metrics/impl/TimeInQueueAction/summary.properties
See [JENKINS-52074](https://issues.jenkins-ci.org/browse/JENKINS-52074)
=> [JENKINS-52074] Metrics plugin does not track pipeline queuing time correctly

src/main/java/jenkins/metrics/api/QueueItemMetricsEvent.java, src/main/java/jenkins/metrics/api/QueueItemMetricsListener.java, src/main/java/jenkins/metrics/impl/JenkinsMetricProviderImpl.java, src/test/java/jenkins/metrics/impl/JenkinsMetricProviderImplTest.java
See [JENKINS-52141](https://issues.jenkins-ci.org/browse/JENKINS-52141)
=> [FIXED JENKINS-52141] Add an extension point for plugins interested in the queue item timings

.mvn/extensions.xml, .mvn/maven.config, pom.xml
[JENKINS-51308](https://issues.jenkins-ci.org/browse/JENKINS-51308)
@stephenc cc @jglick
=> [JEP-305] [JENKINS-51308] Incrementalify Metrics plugin

src/main/java/jenkins/metrics/api/Metrics.java, src/test/java/jenkins/metrics/api/MetricsTest.java
https://issues.jenkins-ci.org/browse/JENKINS-57908
@jglick
=> [JENKINS-57908] Use io.jenkins as jmx domain

src/main/java/jenkins/metrics/api/Metrics.java, src/main/java/jenkins/metrics/impl/ObjectNameFactoryImpl.java, src/test/java/jenkins/metrics/api/MetricsTest.java, src/test/java/jenkins/metrics/impl/ObjectNameFactoryImplTest.java
On top of #47
Commit to review: https://github.com/jenkinsci/metrics-plugin/pull/49/commits/144b6aff601584ea5d29d2b697b95926525c8c23
=> [JENKINS-58169] Re-map ObjectNames to make them follow better JMX practices

README.adoc, src/main/java/jenkins/metrics/impl/JenkinsHealthCheckProviderImpl.java
Terminology updates to replace master with controller. Updated README.adoc, removing master where appropriate, replacing it with controller where needed. 
CloudBees Jira issue https://cloudbees.atlassian.net/browse/BEE-2396
=> [BEE-2396] Terminology update for metrics plugin

pom.xml
@alecharp this resolves the issue with versioning so I could drop this commit in the other PR: https://github.com/jenkinsci/metrics-plugin/pull/174/commits/8b0ec11ea6592729301832e29bd2b265fc3ff918
Bumps `metrics.version` from 4.1.6 to 4.2.10.
Updates `metrics-core` from 4.1.6 to 4.2.10
- [Release notes](https://github.com/dropwizard/metrics/releases)
- [Commits](dropwizard/metrics@v4.1.6...v4.2.10)
Updates `metrics-servlet` from 4.1.6 to 4.2.10
- [Release notes](https://github.com/dropwizard/metrics/releases)
- [Commits](dropwizard/metrics@v4.1.6...v4.2.10)
Updates `metrics-healthchecks` from 4.1.6 to 4.2.10
- [Release notes](https://github.com/dropwizard/metrics/releases)
- [Commits](dropwizard/metrics@v4.1.6...v4.2.10)
Updates `metrics-jvm` from 4.1.6 to 4.2.10
- [Release …
=> Bump metrics.version from 4.1.6 to 4.2.10

src/main/resources/jenkins/metrics/api/MetricsAccessKey/help-accessKeys.html
=> Update links to the metrics code to be dropwizard

README.adoc
As the title suggests,  the documentation has been updated by including "projects" and "task" metrics.
=> Updates metrics documentation

pom.xml, src/main/java/jenkins/metrics/api/MetricsAccessKey.java, src/main/java/jenkins/metrics/api/MetricsRootAction.java, src/main/java/jenkins/metrics/impl/ObjectNameFactoryImpl.java, src/main/java/jenkins/metrics/util/NameRewriterMetricRegistry.java, src/test/java/jenkins/metrics/api/MetricsTest.java
Migrate from deprecated/EOL Commons Lang 2 to Commons Lang 3.
=> Migrate from Commons Lang 2 to Commons Lang 3
